cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'maven'
brew 'node'
brew 'readline'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

cask '1password'
cask 'adium'
cask 'atom'
cask 'google-chrome'
cask 'handbrake'
cask 'iterm2'
cask 'slack'
cask 'steam'
cask 'transmission'
cask 'vlc'
